version: '3.9'
services:
  apache:
    build: .
    image: mvc-apache-php-cms:8.2
    container_name: lamp-apache-cms
    ports:
      - "81:80"                          # Changed from 80 to 81
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: lamp-mysql-cms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data_cms:/var/lib/mysql
    ports:
      - "3308:3306"                      # Changed from 3307 to 3308

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin-cms
    depends_on:
      - mysql
    ports:
      - "8081:80"                        # Changed from 8080 to 8081
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql_data_cms:
